### PR TITLE
Test Sandpack

### PR DESCRIPTION
**Pull request by mellson**
This is a test of how it would feel to use the [Sandpack editor](https://sandpack.codesandbox.io/) over the [twoslash editor](https://shikijs.github.io/twoslash/) we use now.

This is a WIP, and I've only tried to use the Sandpack editor on the actions page - see this page in [the preview deploy](https://docusaurus-docs-git-mellson-test-sandpack-statelyai.vercel.app/actions/).

**Implementation**
I've created a `StatelyEditor` MDX component with some defaults, like loading xstate dependencies.
This way, it's very easy to add the editor inside the mdx files. 

**Initial thoughts**

- It needs some styling to look good
- It's slow compared to twoslash
- Can we use it without the browser preview?

### CODE REVIEW

**Comment by with-heart** [comment]
I know I'm a couple months late here so you might not remember, but how did you find the experience of using Sandpack?

**Comment by mellson** [comment]
> I know I'm a couple months late here so you might not remember, but how did you find the experience of using Sandpack?

To be honest, I felt it was a little too slow to be included in the docs. It takes a little while for the Sandpack editor to load, and the two slash editor is much faster. I think Sandpack now has a slimmer console-only version that I'm yet to test.

Have you tried it? If so what do you think?

**Comment by with-heart** [comment]
I switched to monaco+twoslash from Sandpack for a project for much the same reason. Too slow, codemirror doesn't have the same _feel_ as monaco (bc I'm a vscode user), and I found the Sandpack model of files to be confusing—at least for what I was using it for.

**Comment by mellson** [comment]
> I switched to monaco+twoslash from Sandpack for a project for much the same reason. Too slow, codemirror doesn't have the same _feel_ as monaco (bc I'm a vscode user), and I found the Sandpack model of files to be confusing—at least for what I was using it for.

Thank you, good to know I'm not the only one who feels this way 😊 Will definitely take your feedback into consideration before testing it again 👍🏻

**Comment by mellson** [comment]
I'll close this one for now as it seems we have a good solution in place already with the twoslash editor

**Pull request closed without merging**
