### PR TITLE
Make v5 the default and fix broken links

### PR DESCRIPTION
**Pull request by mellson**

### CODE REVIEW

**Comment by laurakalbag** [comment]
STA-5046

**Review by laurakalbag — APPROVED** [review]

**Comment by derek-primumco** [comment]
Just stopping by to say that changing the URL structure to remove `xstate-v5` without adding redirects made the new docs un-Googleable and broke all my bookmarks 🙃 

https://www.google.com/search?q=xstate+v5+actors
image

image

Old URL https://stately.ai/docs/xstate-v5/actors
New URL https://stately.ai/docs/actors

**Comment by mellson** [comment]
Hi @derek-primumco, thanks for the message, and sorry about breaking your bookmarks 😬 While the docs are in beta, we decided to change the default version to v5 since it's getting released soon. But we probably should have added some redirects; again, sorry about the inconvenience.

**Comment by derek-primumco** [comment]
No worries @mellson! I just wanted to let you know that you should consider redirects when making this type of change.

If I were requesting something, it would be to _remove the old docs from Google via robots.txt or just deleting them_, but I don't care the least bit about the URL structure of the current v5 docs.

On the other hand, I need to be able to find the v5 docs via Google, which is already hard due to the v4 docs.

Without redirects, however, I have been unable to find any v5 docs with Google for more than 2 weeks. For example, https://www.google.com/search?q=v5+docs+stately+actor links to https://stately.ai/docs/xstate-v5/actor-model, which is a broken link.

Thus the feedback: changing the URL structure not only had no benefit to the end user, but it actually made my job _more difficult_ for more than 2 weeks.

**Comment by mellson** [comment]
Thanks for the info @derek-primumco 👍🏻 We have now added redirects, so hopefully, all your links and the search results should work again. Sorry for the trouble

**Comment by derek-primumco** [comment]
No problem @mellson, and thanks for taking care of the redirects!!

**Pull request merged**
