### PR TITLE
Turn docs sidebar category headings into links (and upgrade Docusaurus to 2.4.0)

### PR DESCRIPTION
**Pull request by laurakalbag**
This PR takes the sidebar category headings and turns them into links to (automated) index pages that list all the category’s child pages. I’ve “swizzled” the index page components to make the HTML more valid + semantic and styled them in a similar way to the link boxes on the homepage.

~~This PR turns some of the sidebar category headings into links themselves. Doing this means we can remove redundantly-named child pages (`Intro` etc) into the headings themselves to shorten the nav and make the categories clickable.~~

~~Though now I’ve done it, I’m not sure whether we want it…~~

~~**Pros**:~~
~~- Sidebar is shorter, fewer items in the menus.~~
~~- Sidebar category links actually do something, rather than having `href="#"`, which is annoying when you [try to right click to open a page, or (reasonably) assume that the category is a link itself](https://github.com/statelyai/docs/issues/71).~~

~~**Cons**:~~
~~- It might not be clear to some folks that the category headings are links to pages themselves, so they might miss a whole load of introductory content.~~
~~- Not all category headings are pages themselves, so it’s inconsistent as to whether these are links or not.~~

~~**Possible compromise**:~~
~~1. Keep the intro page links in the child menus as before.~~
~~2. Link the sidebar categories to the intro child pages. (But maybe programmatically hide them from assistive tech/bots as these would be repetitive redundant links.)~~
~~3. Create intro pages for every category, so each sidebar category has a corresponding child page. These pages could just contain brief intros to the topics and link to the pages within.~~

This PR also upgrades to Docusaurus 2.4.0. This can be done in another PR if we don’t end up merging this, it’s not got any breaking changes or updates relevant to us.

### CODE REVIEW

**Comment by laurakalbag** [comment]
@TobiObeck thanks for your feedback on this! I really like the idea of an overview page. And I should probably be able to automate these. That’ll surely be beneficial in helping folks find content via search engines (though we may want to hide these pages from the site search… 🤔.) And you’re right about the `Intro` pages, the content varies and can usually be summarised by something more specific than `Intro`.

**Comment by laurakalbag** [comment]
> I really like the idea of an overview page. And I should probably be able to automate these.

Fabulous, [Docusaurus has this built-in for category links](https://docusaurus.io/docs/sidebar/items#generated-index-page)!

**Comment by TobiObeck** [comment]
Sounds, good to me! And cool that Docusaurus has this built-in

**Review by davidkpiano — APPROVED** [review]
LGTM based on `generated-index` changes - works great!

**Pull request merged**
